spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?autoReconnect=true&createDatabaseIfNotExist=true
    username: root
    password: Gh124578@
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      data-locations: classpath:db/data.sql
      schema-locations: classpath:db/schema.sql
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    defer-datasource-initialization: true